repos:
-   repo: local
    hooks:
<<<<<<< HEAD
    -   id: save-commit-msg
        name: save commit message
        entry: ./bin/save-commit-msg
        verbose: true
        language: script
        stages: [commit-msg]
=======
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      -   id: trailing-whitespace
>>>>>>> 108f308 (feat: add trailing whitespace as pre-commit hook)
